[project]
name = "eye-rest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pillow>=12.2.0",
    "pynput>=1.8.2",
    "pyside6>=6.11.1",
    "pystray>=0.19.5",
    "pywin32>=312",
    "system-hotkey>=1.0.4",
]

[tool.uv.workspace]
members = [
    "eye_rest",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]
